### ISSUE TITLE
Question about default synchronous manner in replication (Sync or Async) 

### ISSUE THREAD

**Issue by liyuntao** [bitnami/bitnami-docker-postgresql-repmgr#19]
I have some doubts about:

1. Whether the image(mainly **postgresql-ha** helm chart) is synchronous or asynchronous by default?
2. Is there a mechanism(config item) that can let the pg cluster switch between synchronous/asynchronous manner?

Some background: recently I met a strange behavior, one of ETL application insert an item for specific job execution. In a short period(within 20ms) the application try to query then update the job status from 'created' to 'starting'. At this moment, there is a noticeable probability that JDBC throws an EmptyResultDataAccessException(Incorrect result size: expected 1, actual 0), but most time, it's ok.

Will there be such a possibility, pgpool route the query to slave instance, and the replication is happened not in-sync at that time?

**Comment by liyuntao** [comment]
Some attempt on pg-cluster's current master node:

```console
postgres=# SHOW synchronous_commit;
 synchronous_commit
--------------------
 on
(1 row)
```
and

```console
postgres=# SELECT pid, client_addr, state, sync_state FROM pg_stat_replication;
  pid  | client_addr  |   state   | sync_state
-------+--------------+-----------+------------
 12552 | 10.233.69.23 | streaming | async
 12686 | 10.233.71.16 | streaming | async
(2 rows)
```

Will the two results showing inconsistent with each other?

**Comment by dani8art** [comment]
Hi @liyuntao, I think maybe it could be difficult to solve such as we have pg-pool load balancing so the synchronization of the pg could not happen until some ms after. This might help you https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/values.yaml#L447. With that maybe the query is going to the same slave you can avoid this.

Other way to do it is to solve this as code level, I mean, you make sure that the `job` row exists before update its values. 

Otherwise, there should be a way to configure your app to do synchronous commits, I mean, even if the cluster by default uses asynchronous way of doing a commit, you could have the possibility of doing it synchronously.

**Comment by liyuntao** [comment]
Hi @dani8art , thank you very much for these valuable suggestions. Sadly the code level modification may not suitable because the behavior in the above background is spring-batch frameworks manner. However, the suggestions are helpful for me to write code level logic when using asynchronous pg-cluster.

I'll take a try on arg `useLoadBalancing` first. It seems a feasible solution.

**Comment by dani8art** [comment]
Good to hear! don't hesitate to contact us if this was not feasible for you. Thanks

**Comment by greenenvy2** [comment]
Does anyone can explain how to setup synchronous replication with the image? I managed to do so without repmgr on the standard postgres image without any problems, but im struggling to do it here. The default replication setup is async.

**Comment by dani8art** [comment]
Hi @greenenvy2 could you share with us more detailed steps? I mean, what have you tried?
