### ISSUE TITLE
Outage during failover

### ISSUE THREAD

**Issue by morot** [bitnami/bitnami-docker-postgresql-repmgr#27]
**Description**

Thanks bitnami for great charts, Im using the postgresql-ha chart deployed on k8s.
When I delete the primary DB pod I'm getting an outage for 20 sec before the standby has taken over the role of primary, is that expected? The App is using the pgpool service and  chart=postgresql-ha-3.4.3

**Steps to reproduce the issue:**

Deploy  helm.sh/chart=postgresql-ha-3.4.3
I use keycloak as an app which where dbHost is set keycloak-db-postgresql-ha-pgpool (pgpool svc name) or use any a postgresql client.

1. delete the primary postgresql pod

**Describe the results you received:**

Keycloak or client goes away for 20 sec while failover is happening, and I'm having a 20 second outage

**Describe the results you expected:**

Is it expected that clients drop off and then reconnect or should the failover be seamless?

**Comment by marcosbc** [comment]
@morot That is expected behavior with the default configuration. Note that instantaneous failover is not something that would be supported, in any case, failovers shouldn't occur too much often either so there shouldn't be much to worry about.

However, note that you can optimize the time by changing the health check configurations. See: https://www.pgpool.net/docs/latest/en/html/runtime-config-health-check.html

To see how to include the custom configuration parameters, you can refer to [this comment](https://github.com/bitnami/charts/issues/3127#issuecomment-659319056) in a past issue.

**Comment by morot** [comment]
Thank you.
