### ISSUE TITLE
The second node stops at the cluster after connecting

### ISSUE THREAD

**Issue by AhmadRafiee** [bitnami/bitnami-docker-postgresql-repmgr#53]
The second node stops at the cluster after connecting. 
This problem did not exist before but is now found in versions 12 and 13.
But in version 11 it is still correct and without problems.

**docker logs on the primary node:**
```
[NOTICE] repmgrd (repmgrd 5.2.0) starting up
INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
[NOTICE] starting monitoring of node "pg-0" (ID: 1000)
[NOTICE] monitoring cluster primary "pg-0" (ID: 1000)
[NOTICE] new standby "pg-1" (ID: 1001) has connected

```

**docker logs on the secondary node:**
```
Welcome to the Bitnami postgresql-repmgr container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues

INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
INFO  ==> Validating settings in REPMGR_* env vars...
INFO  ==> Validating settings in POSTGRESQL_* env vars..
INFO  ==> Querying all partner nodes for common upstream node...
INFO  ==> Preparing PostgreSQL configuration...
INFO  ==> postgresql.conf file not detected. Generating it...
INFO  ==> Preparing repmgr configuration...
INFO  ==> Initializing Repmgr...
INFO  ==> Waiting for primary node...
INFO  ==> Cloning data from primary node...
INFO  ==> Initializing PostgreSQL database...
INFO  ==> Cleaning stale /bitnami/postgresql/data/standby.signal file
INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
INFO  ==> Deploying PostgreSQL with persisted data...
INFO  ==> Configuring replication parameters
INFO  ==> Configuring fsync
INFO  ==> Setting up streaming replication slave...
INFO  ==> Starting PostgreSQL in background...
INFO  ==> Unregistering standby node...
INFO  ==> Registering Standby node...
INFO  ==> Running standby follow...
INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
```
**docker-compose ps**
```
      Name                    Command                State             Ports         
-------------------------------------------------------------------------------------
debian-10_pg-0_1   /opt/bitnami/scripts/postg ...   Up        0.0.0.0:32774->5432/tcp
debian-10_pg-1_1   /opt/bitnami/scripts/postg ...   Exit 23                          

```

**Comment by Jacq** [comment]
Exactly the same behavior here, but using the bitnami helm chart that includes this image.

**Comment by andresbono** [comment]
Hi @AhmadRafiee, @Jacq, thanks for reporting this issue. We think it might be related to #30. We will be investigating it and we will get back to you. If you get any new findings, please add a comment either here or in #30.

**Comment by mc-marcy** [comment]
same issue with version 13 r6. this is the debug output

`
pg-2_1  | [REPMGR EVENT::standby_follow] Node id: 1002; Event type: standby_follow; Success [1|0]: 0; Time: 2020-11-18 20:21:32.282729+00;  Details: slot "repmgr_slot_1002" already exists as an active slot

pg-2_1  | [REPMGR EVENT::standby_follow] The event failed! No need to do anything.
pg-2_1  | WARNING: unable to execute event notification command
pg-2_1  | DETAIL: parsed event notification command was:
pg-2_1  |   /opt/bitnami/repmgr/events/router.sh 1002 standby_follow 0 "2020-11-18 20:21:32.282729+00" "slot \"repmgr_slot_1002\" already exists as an active slot
pg-2_1  | "
pg-2_1  | NOTICE: STANDBY FOLLOW failed
pg-2_1  | DETAIL: slot "repmgr_slot_1002" already exists as an active slot
pg-2_1  |
pg-2_1  | postgresql-repmgr 20:21:32.31 INFO  ==> Stopping PostgreSQL...
pg-2_1  | waiting for server to shut down....2020-11-18 20:21:32.323 GMT [185] LOG:  received fast shutdown request
pg-2_1  | 2020-11-18 20:21:32.324 GMT [185] LOG:  aborting any active transactions
pg-2_1  | 2020-11-18 20:21:32.324 GMT [191] FATAL:  terminating walreceiver process due to administrator command
pg-2_1  | 2020-11-18 20:21:32.326 GMT [188] LOG:  shutting down
pg-2_1  | 2020-11-18 20:21:32.409 GMT [185] LOG:  database system is shut down
pg-2_1  |  done
pg-2_1  | server stopped
postgres_pg-2_1 exited with code 23
`

same docker config with latest container (version 11) is working fine

**Comment by andresbono** [comment]
Hi @mc-marcy, thanks for sharing the logs output with debug enabled. We continue investigating the issue.

**Comment by Jacq** [comment]
Hi, just tested version 13.1.0-debian-10-r11 with debug enabled I see a similar error message about slot already exists, but there is a previous error message related to the node-id not not found:

<pre>
postgres             | postgresql-repmgr 22:51:01.56 INFO  ==> Cloning data from primary node...
postgres             | WARNING: following problems with command line parameters detected:
postgres             |   -D/--pgdata will be ignored if a repmgr configuration file is provided
postgres             | NOTICE: destination directory "/bitnami/postgresql/data" provided
postgres             | NOTICE: checking for available walsenders on the source node (2 required)
postgres             | NOTICE: checking replication connections can be made to the source server (2 required)
postgres             | WARNING: data checksums are not enabled and "wal_log_hints" is "off"
postgres             | DETAIL: pg_rewind requires "wal_log_hints" to be enabled
postgres             | NOTICE: starting backup (using pg_basebackup)...
postgres             | NOTICE: standby clone (using pg_basebackup) complete
postgres             | NOTICE: you can now start your PostgreSQL server
postgres             | HINT: for example: pg_ctl -D /bitnami/postgresql/data start
postgres             | HINT: after starting the server, you need to register this standby with "repmgr standby register"
postgres             | [REPMGR EVENT] Node id: 1002; Event type: standby_clone; Success [1|0]: 1; Time: 2020-11-24 22:51:02.880516+00;  Details: cloned from host "db-1", port 5432; backup method: pg_basebackup; --force: Y
postgres             | Looking for the script: /opt/bitnami/repmgr/events/execs/standby_clone.sh
postgres             | [REPMGR EVENT] no script '/opt/bitnami/repmgr/events/execs/standby_clone.sh' found. Skipping...
postgres             | postgresql-repmgr 22:51:03.21 INFO  ==> Initializing PostgreSQL database...
postgres             | postgresql-repmgr 22:51:03.22 INFO  ==> Cleaning stale /bitnami/postgresql/data/standby.signal file
postgres             | postgresql-repmgr 22:51:03.23 DEBUG ==> Copying files from /bitnami/postgresql/conf to /opt/bitnami/postgresql/conf
postgres             | postgresql-repmgr 22:51:03.24 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgres             | postgresql-repmgr 22:51:03.25 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgres             | postgresql-repmgr 22:51:03.26 DEBUG ==> Ensuring expected directories/files exist...
postgres             | postgresql-repmgr 22:51:03.31 INFO  ==> Deploying PostgreSQL with persisted data...
postgres             | postgresql-repmgr 22:51:03.38 INFO  ==> Configuring replication parameters
postgres             | postgresql-repmgr 22:51:03.46 INFO  ==> Configuring fsync
postgres             | postgresql-repmgr 22:51:03.51 INFO  ==> Setting up streaming replication slave...
postgres             | postgresql-repmgr 22:51:03.58 INFO  ==> Starting PostgreSQL in background...
postgres             | waiting for server to start....2020-11-24 22:51:03.654 GMT [185] LOG:  pgaudit extension initialized
postgres             | 2020-11-24 22:51:03.671 GMT [185] LOG:  redirecting log output to logging collector process
postgres             | 2020-11-24 22:51:03.671 GMT [185] HINT:  Future log output will appear in directory "/opt/bitnami/postgresql/logs".
postgres             | 2020-11-24 22:51:03.671 GMT [185] LOG:  starting PostgreSQL 13.1 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres             | 2020-11-24 22:51:03.673 GMT [185] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres             | 2020-11-24 22:51:03.673 GMT [185] LOG:  listening on IPv6 address "::", port 5432
postgres             | 2020-11-24 22:51:03.677 GMT [185] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
postgres             | 2020-11-24 22:51:03.684 GMT [187] LOG:  database system was interrupted; last known up at 2020-11-24 22:51:01 GMT
postgres             | 2020-11-24 22:51:03.765 GMT [187] LOG:  entering standby mode
postgres             | 2020-11-24 22:51:03.769 GMT [187] LOG:  redo starts at 0/4000028
postgres             | 2020-11-24 22:51:03.772 GMT [187] LOG:  consistent recovery state reached at 0/4000100
postgres             | 2020-11-24 22:51:03.772 GMT [185] LOG:  database system is ready to accept read only connections
postgres             | 2020-11-24 22:51:03.786 GMT [191] LOG:  started streaming WAL from primary at 0/5000000 on timeline 1
postgres             |  done
postgres             | server started
postgres             | postgresql-repmgr 22:51:03.84 INFO  ==> Unregistering standby node...
postgres             | ERROR: node 1002 (specified with --node-id) not found
postgres             | postgresql-repmgr 22:51:03.90 INFO  ==> Registering Standby node...
postgres             | NOTICE: using provided configuration file "/opt/bitnami/repmgr/conf/repmgr.conf"
postgres             | WARNING: --upstream-node-id not supplied, assuming upstream node is primary (node ID 1001)
postgres             | [REPMGR EVENT] Node id: 1002; Event type: standby_register; Success [1|0]: 1; Time: 2020-11-24 22:51:03.908781+00;  Details: standby registration succeeded; upstream node ID is 1001 (-F/--force option was used)
postgres             | Looking for the script: /opt/bitnami/repmgr/events/execs/standby_register.sh
postgres             | [REPMGR EVENT] no script '/opt/bitnami/repmgr/events/execs/standby_register.sh' found. Skipping...
postgres             | NOTICE: standby node "db-2" (ID: 1002) successfully registered
postgres             | postgresql-repmgr 22:51:04.00 INFO  ==> Running standby follow...
postgres             | NOTICE: using provided configuration file "/opt/bitnami/repmgr/conf/repmgr.conf"
postgres             | WARNING: following problems with command line parameters detected:
postgres             |   --no-wait will be ignored when executing STANDBY FOLLOW
postgres             | DEBUG: do_standby_follow()
postgres             | DEBUG: connecting to: "user=repmgr password=**********************. connect_timeout=5 dbname=repmgr host=db-2 port=5432 fallback_application_name=repmgr options=-csearch_path="
postgres             | DEBUG: set_config():
postgres             |   SET synchronous_commit TO 'local'
postgres             | INFO: connected to local node
postgres             | DEBUG: get_recovery_type(): SELECT pg_catalog.pg_is_in_recovery()
postgres             | DEBUG: get_node_record():
postgres             |   SELECT n.node_id, n.type, n.upstream_node_id, n.node_name,  n.conninfo, n.repluser, n.slot_name, n.location, n.priority, n.active, n.config_file, '' AS upstream_node_name, NULL AS attached   FROM repmgr.nodes n  WHERE n.node_id = 1002
postgres             | NOTICE: attempting to find and follow current primary
postgres             | INFO: searching for primary node
postgres             | DEBUG: get_primary_connection():
postgres             |   SELECT node_id, conninfo,          CASE WHEN type = 'primary' THEN 1 ELSE 2 END AS type_priority          FROM repmgr.nodes    WHERE active IS TRUE      AND type != 'witness' ORDER BY active DESC, type_priority, priority, node_id
postgres             | INFO: checking if node 1001 is primary
postgres             | DEBUG: connecting to: "user=repmgr password=**********************. connect_timeout=5 dbname=repmgr host=db-1 port=5432 fallback_application_name=repmgr options=-csearch_path="
postgres             | DEBUG: set_config():
postgres             |   SET synchronous_commit TO 'local'
postgres             | DEBUG: get_recovery_type(): SELECT pg_catalog.pg_is_in_recovery()
postgres             | INFO: current primary node is 1001
postgres             | INFO: connected to node 1001, checking for current primary
postgres             | DEBUG: get_node_record():
postgres             |   SELECT n.node_id, n.type, n.upstream_node_id, n.node_name,  n.conninfo, n.repluser, n.slot_name, n.location, n.priority, n.active, n.config_file, '' AS upstream_node_name, NULL AS attached   FROM repmgr.nodes n  WHERE n.node_id = 1001
postgres             | DEBUG: get_recovery_type(): SELECT pg_catalog.pg_is_in_recovery()
postgres             | INFO: follow target is primary node "db-1" (ID: 1001)
postgres             | DEBUG: local timeline: 1; follow target timeline: 1
postgres             | INFO: timelines are same, this server is not ahead
postgres             | DETAIL: local node lsn is 0/50005E8, follow target lsn is 0/50005E8
postgres             | DEBUG: get_node_record():
postgres             |   SELECT n.node_id, n.type, n.upstream_node_id, n.node_name,  n.conninfo, n.repluser, n.slot_name, n.location, n.priority, n.active, n.config_file, '' AS upstream_node_name, NULL AS attached   FROM repmgr.nodes n  WHERE n.node_id = 1002
postgres             | INFO: creating replication slot as user "repmgr"
postgres             | DEBUG: get_slot_record():
postgres             | SELECT slot_name, slot_type, active   FROM pg_catalog.pg_replication_slots  WHERE slot_name = 'repmgr_slot_1002'
postgres             | ERROR: slot "repmgr_slot_1002" already exists as an active slot
postgres             |
postgres             | DEBUG: _create_event(): event is "standby_follow" for node 1002
postgres             | DEBUG: get_recovery_type(): SELECT pg_catalog.pg_is_in_recovery()
postgres             | DEBUG: _create_event():
postgres             |    INSERT INTO repmgr.events (              node_id,              event,              successful,              details             )       VALUES ($1, $2, $3, $4)    RETURNING event_timestamp
postgres             | DEBUG: _create_event(): Event timestamp is "2020-11-24 22:51:03.996318+00"
postgres             | DEBUG: _create_event(): command is '/opt/bitnami/repmgr/events/router.sh %n %e %s "%t" "%d"'
postgres             | INFO: executing notification command for event "standby_follow"
postgres             | DETAIL: command is:
postgres             |   /opt/bitnami/repmgr/events/router.sh 1002 standby_follow 0 "2020-11-24 22:51:03.996318+00" "slot \"repmgr_slot_1002\" already exists as an active slot
postgres             | "
postgres             | [REPMGR EVENT] Node id: 1002; Event type: standby_follow; Success [1|0]: 0; Time: 2020-11-24 22:51:03.996318+00;  Details: slot "repmgr_slot_1002" already exists as an active slot
postgres             |
postgres             | Looking for the script: /opt/bitnami/repmgr/events/execs/standby_follow.sh
postgres             | [REPMGR EVENT] will execute script '/opt/bitnami/repmgr/events/execs/standby_follow.sh' for the event
postgres             | [REPMGR EVENT::standby_follow] Node id: 1002; Event type: standby_follow; Success [1|0]: 0; Time: 2020-11-24 22:51:03.996318+00;  Details: slot "repmgr_slot_1002" already exists as an active slot
postgres             |
postgres             | [REPMGR EVENT::standby_follow] The event failed! No need to do anything.
postgres             | WARNING: unable to execute event notification command
postgres             | DETAIL: parsed event notification command was:
postgres             |   /opt/bitnami/repmgr/events/router.sh 1002 standby_follow 0 "2020-11-24 22:51:03.996318+00" "slot \"repmgr_slot_1002\" already exists as an active slot
postgres             | "
postgres             | NOTICE: STANDBY FOLLOW failed
postgres             | DETAIL: slot "repmgr_slot_1002" already exists as an active slot
postgres             |
postgres             | postgresql-repmgr 22:51:04.10 INFO  ==> Stopping PostgreSQL...
postgres             | waiting for server to shut down....2020-11-24 22:51:04.113 GMT [185] LOG:  received fast shutdown request
postgres             | 2020-11-24 22:51:04.115 GMT [185] LOG:  aborting any active transactions
postgres             | 2020-11-24 22:51:04.117 GMT [191] FATAL:  terminating walreceiver process due to administrator command
postgres             | 2020-11-24 22:51:04.118 GMT [188] LOG:  shutting down
postgres             | 2020-11-24 22:51:04.126 GMT [185] LOG:  database system is shut down
postgres             |  done
postgres             | server stopped

</pre>

**Comment by juan131** [comment]
Hi everyone,

In order to avoid confusion and repetition, I proceed to close this issue since we are already tracking this particular bug in the issue below:

- https://github.com/bitnami/charts/issues/4414

Please, let's follow the conversation there.

Thanks for reporting it!
