### ISSUE TITLE
How to use PostgreSQL scheduler using pg_cron extension in current image?

### ISSUE THREAD

**Issue by devang704** [bitnami/bitnami-docker-postgresql-repmgr#64]
**Description**

I want to use scheduler in postgresql database which is supported by installing pg_cron extension.

I am new to Docker image, How to install pg_cron library in image?

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by devang704** [comment]
Hi Team,

**Comment by miguelaeh** [comment]
Hi @devang704 ,
Did you find the solution?

**Comment by devang704** [comment]
I have tried to install package "postgresql-11-cron" but its installing in default path /usr/lib/postgresql/11... which is not identified by postgres while setting shared_pre_load_libraries='pg_cron'. It is not working, Please suggest changes required to suppport pg_cron extension or let me know if i am doing anything wrong?

**Comment by devang704** [comment]
I have used below link to install package : 
https://debian.pkgs.org/10/debian-main-amd64/postgresql-11-cron_1.1.3-2_amd64.deb.html

**Comment by miguelaeh** [comment]
Hi @devang704 ,
Give a try to use this dockerfile:
```
FROM bitnami/postgresql:13.1.0-debian-10-r29
USER root
RUN install_packages postgresql-11-cron && \
USER 1001
```
and add this to the setup.sh:

```diff
  repmgr_postgresql_configuration
  # Prepare repmgr configuration
  repmgr_generate_repmgr_config
+ sed -r -i "s/shared_preload_libraries = \'(.*)\'/shared_preload_libraries = \'\1,pg_cron\'/g" /opt/bitnami/postgresql/conf/postgresql.conf
  # Initialize PostgreSQL & repmgr
  repmgr_initialize
```

**Comment by devang704** [comment]
Hi @miguelaeh Thank you for your reply!

I am using postgresql11 image bitnami/postgresql:11.10.0, can I do suggested changes in same image?

Do I need to change in DockerFile and rebuild image?

**Comment by miguelaeh** [comment]
Hi @devang704 ,
The same changes could be applied to version `11`. Just edit the Dockerfile to use the base image you are using (don't forget to change the package version as well at the install_packages command).
The change to the script should still apply, since they are the same.
The detailed steps are the following:
1. Clone this repo
2. Move to the directory `11`
2. Modify the `setup.sh` under the `rootfs` with the change above.
3. Build the postgresql image: `docker build . -t <your-tag>`
4. Create the Dockerfile above and set `<tour-tag>` in the `FROM` line.
5. Build that image

If you don't want to build those images in separate steps, you can add the installation of `postgresql-11-cron` to the PostgreSQL Dockerfile before building the first time. I mean, in the same step you are modifying the `setup.sh`. So you just need to build once.

**Comment by devang704** [comment]
Hi @miguelaeh,

As per your suggestion, I have followed below steps to deploy PostgreSQL with pg_cron extension.

1. Clone git repo
2. Edit DockerFile - added "postgresql-11-cron" in existing RUN command
+ RUN install_packages acl ca-certificates curl gzip libbsd0 libc6 libedit2 libffi6 libgcc1 libgmp10 libgnutls30 libhogweed4 libicu63 libidn2-0 libldap-2.4-2 liblzma5 libnettle6 libp11-kit0 libsasl2-2 libsqlite3-0 libssl1.1 libstdc++6 libtasn1-6 libtinfo6 libunistring2 libuuid1 libxml2 libxslt1.1 locales procps tar zlib1g postgresql-11-cron

3. Modify setup.sh file ./rootfs/opt/bitnami/scripts/postgresql-repmgr/setup.sh by adding below line
  repmgr_postgresql_configuration
  # Prepare repmgr configuration
  repmgr_generate_repmgr_config
+ sed -r -i "s/shared_preload_libraries = \'(.*)\'/shared_preload_libraries = \'\1,pg_cron\'/g" /opt/bitnami/postgresql/conf/postgresql.conf
  # Initialize PostgreSQL & repmgr
  repmgr_initialize

4. Build new docker image and started container with below docker run command and checked container-logs using docker logs. Container started successfully but shared_preload_libraries parameter not modified in postgresql.conf parameterfile.

docker run -itd --name pg-0 \
  --network my-network \
  --env REPMGR_PARTNER_NODES=pg-0,pg-1 \
  --env REPMGR_NODE_NAME=pg-0 \
  --env REPMGR_NODE_NETWORK_NAME=pg-0 \
  --env REPMGR_PRIMARY_HOST=pg-0 \
  --env REPMGR_PASSWORD=repmgr \
  --env POSTGRESQL_PASSWORD=postgres \
  repository.local.com:5050/postgresql-repmgr:11.10.0

5. I have run below sed command inside container to change shared_preload_libraries parameter in containers postgresql.conf file and restart postgres service using pg_ctl command but it throws error as below. I have checked pg_cron file located /usr/lib/postgresql/11/lib/pg_cron.so location.

[ec2-user@-cluster ~]$ docker exec -it pg-0 bash
I have no name!@dc9440c97038:/bitnami/postgresql/conf$ sed -i "s/shared_preload_libraries = .*/shared_preload_libraries = 'repmgr, pgaudit, pg_cron'/g" /opt/bitnami/postgresql/conf/postgresql.conf
I have no name!@dc9440c97038:/bitnami/postgresql/conf$
I have no name!@dc9440c97038:/bitnami/postgresql/conf$ /opt/bitnami/postgresql/bin/pg_ctl -D /bitnami/postgresql/data restart
2020-12-17 08:43:48.279 GMT [335] LOG:  received fast shutdown request
waiting for server to shut down....2020-12-17 08:43:48.281 GMT [335] LOG:  aborting any active transactions
2020-12-17 08:43:48.281 GMT [346] FATAL:  terminating connection due to administrator command
2020-12-17 08:43:48.285 GMT [335] LOG:  background worker "logical replication launcher" (PID 344) exited with exit code 1
2020-12-17 08:43:48.286 GMT [338] LOG:  shutting down
2020-12-17 08:43:48.386 GMT [335] LOG:  database system is shut down
 done
server stopped
waiting for server to start....2020-12-17 08:43:48.493 GMT [382] LOG:  pgaudit extension initialized
2020-12-17 08:43:48.493 GMT [382] FATAL:  could not access file "pg_cron": No such file or directory
2020-12-17 08:43:48.494 GMT [382] LOG:  database system is shut down
 stopped waiting
pg_ctl: could not start server
Examine the log output.
I have no name!@dc9440c97038:/bitnami/postgresql/conf$

Please suggest the changes required for pg_cron extension...

**Comment by marcosbc** [comment]
Hi @devang704, sorry for the delay, due to christmas holidays things are going a bit slower than usual.

Unfortunately we cannot guarantee for the pg_cron module from Debian to be compatible with Bitnami's. Instead, we'd recommend you to build the extension on your side and install it onto Bitnami PostgreSQL's Docker image.

See an example here: https://github.com/bitnami/bitnami-docker-postgresql/issues/249#issuecomment-699037416 - You'd need to adapt the code snippet for building pg_cron, and add that to your Dockerfile, but that's it.

**Comment by devang704** [comment]
Hi @marcosbc,

I have created custom image by making changes to Dockerfile, and handled to deploy pgcron extension in image.

**Comment by matt-best-elateral** [comment]
Hi.  I realise that this issue is closed.  For anyone experiencing the same problem, and who stumbles across this page, this is the solution that worked for me.

1.  Create a new image using the following Dockerfile:
```
FROM  bitnami/postgresql:11.10.0-debian-10-r0
USER root
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
        postgresql-11-cron \
    && rm -rf /var/lib/apt/lists/ \
    && cp /usr/lib/postgresql/11/lib/pg_cron.so /opt/bitnami/postgresql/lib \
    && cp /usr/share/postgresql/11/extension/pg_cron* /opt/bitnami/postgresql/share/extension \
    && chmod +x /opt/bitnami/postgresql/lib/pg_cron.so
USER 1001
```
2.  If using docker-compose, set the following environment variable:
```
POSTGRESQL_SHARED_PRELOAD_LIBRARIES: "pgaudit,pg_cron"
```
3.  If using the bitnami helm chart, I expect that the following setting will be required:
```
postgresqlSharedPreloadLibraries: "pgaudit,pg_cron"
```

**Comment by cathyalex** [comment]
Hi @matt-best-elateral .. Created a customised docker image as suggested by you. But can you pls let know how to use the custom image in bitnami helm chart values.yaml file?

For instance, I have created a customised postgres image as mentioned -which includes pg_cron extension in our server, but not able to use the custom image from our server via values.yaml file provided by bitnami.

Tried to use the customized image as shown below but since 'registry' parameter default value is set to 'docker.io', it is not taking the image from server. It is showing image pull error. Tried changing the image pull policy to 'Never' as well.
image:
  #registry: docker.io
  #repository: bitnami/postgresql
  #tag: 12.7.0-debian-10-r47
  repository: custom-postgres
  tag: 1.0
  pullPolicy: IfNotPresent

Thanks

**Comment by miguelaeh** [comment]
Hi @cathyalex ,
You need to push the image to some registry in order to use it, then configure the image registry to point to the registry where you pushed the image

**Comment by matt-best-elateral** [comment]
An abridged version of my yaml file looks a bit like this:
```
$ cat postgresql.yaml

image:
  repository: my-docker-repo/my-postgresql
  tag: 11.10.0
  pullSecrets:
    - my-docker-creds
postgresqlPassword: XXX
postgresqlDatabase: XXX
postgresqlSharedPreloadLibraries: "pgaudit,pg_cron"
```

**Comment by matt-best-elateral** [comment]
I deploy using helm, using the yaml file that I created:
```
helm upgrade --install --namespace my-namespace --values ./postgresql.yaml --version 9.8.12 my-namespace-postgres bitnami/postgresql
```

**Comment by cathyalex** [comment]
Thanks @matt-best-elateral . I have pushed the custom image to the registry and now postgres is installed sucecsfully via bitnami helm chart.

However, while I try to create extension in my custom db - its throwing the below error.

**ERROR:  can only create extension in database postgres
DETAIL:  Jobs must be scheduled from the database configured in cron.database_name, since the pg_cron background worker reads job descriptions from this database.
HINT:  Add cron.database_name = 'active-monitoring' in postgresql.conf to use the current database.
CONTEXT:  PL/pgSQL function inline_code_block line 4 at RAISE
SQL state: P0001**

I tried adding the below parameter in values.yaml file but it looks like this parameter is not taken by postgresql.conf file inside the container.
**cron.database_name = 'active-monitoring'**

Could you please suggest how to incorporate the cron.database_name parameter in values.yaml file?

PS: I could create pg_cron extension for default 'postgres' database. But not able to do the same for 'active-monitoring' db.

Thanks

**Comment by matt-best-elateral** [comment]
Hi @cathyalex .  I created the cron extenson in the `postgres` database and then when creating the job included the name of the database against which I wanted the query to be run.

```
select * from cron.job
```
```
jobid | schedule | command | nodename | nodeport | database | username | active
--- | --- | --- | --- | --- | --- | --- | ---
1 | */5 * * * * | SELECT public.refresh_materialized_views() | localhost | 5432 | my-database | my-postgres-user | true 
```

**Comment by matt-best-elateral** [comment]
I set the database for the job with the following:
```
DO $$
DECLARE job_id bigint := cron.schedule('*/5 * * * *', 'SELECT public.refresh_materialized_views()');
BEGIN
        UPDATE cron.job
        SET database = 'my-database'
        WHERE jobid = @jobid;
END $$;
```

**Comment by cathyalex** [comment]
Thanks @matt-best-elateral. I have created a custom image which will set the "cron.database_name = 'active-monitoring'" along with pg_cron extenstion. Now Im able to create pg_cron extension and create jobs in my 'active-monitoring' db itself.

However, the scheduled jobs are not getting executed.  
Below is the sample job scheduled for every 1 minute and have updated the nodename and nodeport to which i have exposed my db and external port.

**SELECT cron.schedule('* * * * *',$$DELETE FROM public."alerts_alarm" WHERE severity =0$$);
UPDATE cron.job SET nodename='my-server-ip', nodeport=30500;**

Could you please let know if we need to do any specific changes in pf_hba.conf file or .pass file for the cron job to run without any password?

**Comment by matt-best-elateral** [comment]
Hi @cathyalex .  I'm afraid that I don't know the answer.  Is the cron expression in your example - `* * *` - correct (perhaps the formatting of the comment changed the value)?  If you want it every minute then try `*/1 * * * *`.

**Comment by cathyalex** [comment]
Hi @matt-best-elateral,
Sorry that was a typo. Below is the expression I have used,
SELECT cron.schedule('* * * * *',$$DELETE FROM public."alerts_alarm" WHERE severity=0$$);

Tried the same with below as well but no luck. Not sure why the scheduled jobs are not getting executed.
SELECT cron.schedule('*/1 * * * *',$$DELETE FROM public."alerts_alarm" WHERE severity=0$$);

Thanks

**Comment by matt-best-elateral** [comment]
@cathyalex I've re-read the script I posted for the Dockerfile and can see that there was a line missing:
```
RUN sed -i '1ilocal    all             postgres                                peer' /opt/bitnami/postgresql/conf/pg_hba.conf
```
I've updated my earlier comment to include this line.  See https://www.postgresql.org/docs/9.1/auth-pg-hba-conf.html for details of this file.

**Comment by cathyalex** [comment]
Hi @matt-best-elateral,
My postgres is installed in remote server. (i.e) jump server is required to connect to my server where postgres is installed in k8s. 
I have exposed the postgres app pod to external port- 30500 - thats why im updating nodename as my 'k8s master server ip' and nodeport as 'port exposed externally'.

**SELECT cron.schedule(' * * * * * ',$$DELETE FROM public."alerts_alarm" WHERE severity =0$$);
UPDATE cron.job SET nodename='my-server-ip', nodeport=30500;**

Could you please let know if adding the below in image would work for my above scenario? should i try the entry with 'host' and 'trust' authentication instead of 'local' and 'peer'? Thanks in advance

RUN sed -i '1ilocal    all             postgres                                peer' /opt/bitnami/postgresql/conf/pg_hba.conf

**Comment by matt-best-elateral** [comment]
Hi @cathyalex .  I'm afraid I do not know the answer. The examples I gave work for the set up we have.

**Comment by cathyalex** [comment]
ok thanks @matt-best-elateral . Will give it a try and let you know!

**Comment by cathyalex** [comment]
Hi @matt-best-elateral .. Just thought  of providing an update as it might be useful for someone.

I could not incorporate the sed command which you have mentioned above in the Docker file as it is not overriding the existing pg_hba.conf file content. 
I have tried quite a few of sed, cat and echo commands as shown below but nothing seemed to be working. (I could build image but the default pg_hba file values are not getting replaced)

RUN sed -i 's/md5/trust/g' /opt/bitnami/postgresql/conf/pg_hba.conf
RUN sed "s/md5/trust/g" /opt/bitnami/postgresql/conf/pg_hba.conf
RUN cat /opt/bitnami/postgresql/conf/pg_hba.conf | sed "s/md5/trust/g"

So finally, i found a way to add the pg_hba.conf file content in values.yaml file itself under 'pgHbaConfiguration' section as shown below. (bitnami/postgres helm chart values.yaml)

pgHbaConfiguration: |-
  host     all             all             0.0.0.0/0               trust
  host     all             all             ::/0                    trust
  local    all             all                                     trust
  host     all             all        127.0.0.1/0                  trust
  host     all             all        ::1/128                      trust

This worked for me and database connection failure issue had resolved. Now the scheduled jobs are getting executed without any issues :)

Thanks heaps for your suggestions @matt-best-elateral

**Comment by matt-best-elateral** [comment]
I'm glad you managed to work out your answer, @cathyalex .
