### ISSUE TITLE
Could not start docker service because outdate version repmgr v.5.2

### ISSUE THREAD

**Issue by tuantmtb** [bitnami/bitnami-docker-postgresql-repmgr#98]
Deploy via docker-compose
Image: bitnami/postgresql-repmgr:12-debian-10

```
[2021-11-19 20:10:10] [NOTICE] repmgrd (repmgrd 5.3) starting up
[2021-11-19 20:10:10] [ERROR] an older version of the "repmgr" extension is installed
[2021-11-19 20:10:10] [DETAIL] extension version 5.2 is installed but newer version 5.3 is available
[2021-11-19 20:10:10] [HINT] verify the repmgr installation is updated properly before continuing
```

How can I fix this?

Thank for your help !

**Comment by migruiz4** [comment]
Hi @tuantmtb,

This issue is a duplicated of https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues/50.

Your problem can be solved by adding the following environment variable to your container: `REPMGR_UPGRADE_EXTENSION=yes`

This will run the command `ALTER EXTENSION repmgr UPDATE` in your database before starting repmgr, fixing the error message.

https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/61a884770e7ebfe5ec0aa7b6f8128e632a60ec63/9.6/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh#L672-L676

**Comment by wjkw1** [comment]
Anyone having this same issue using Kubernetes/Rancher **postgres-ha** install see below:

The equivalent enviroment variable for `REPMGR_UPGRADE_EXTENSION=yes` is `postgresql.upgradeRepmgrExtension=true`

For a smooth upgrade from lower postgresql install you'll need to also specify the `postgresql.replicaCount=1`

More detail here:
https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha#to-800

**Comment by migruiz4** [comment]
Thank you @wjkw1!
 
Indeed, when using the `postgresql-ha` chart the value `postgresql.upgradeRepmgrExtension` can be used to set `REPMGR_UPGRADE_EXTENSION`.

I will now close this issue, if you have any further issues please let me know.

**Comment by tuantmtb** [comment]
Thank you for your help @wjkw1  @migruiz4 . I've solved it.
